use Ginasio;

INSERT INTO Exercicio (idexercicio,Descricao,Tipo)
  VALUES (1,'Agachamentos','Pernas'),
                 (2,'Prensa','Pernas'),
                 (3,'Martelo','Bícep'),
                 (4,'Preacher Curl','Bícep'),
                 (5,'Curl Invertido','Bícep'),
                 (6,'Fundos','Trícep'),
                 (7,'Puxador Trícep Corda','Trícep'),
                 (8,'Trícep Francês','Trícep'),
                 (9,'Supino Inclinado','Peito'),
                 (10,'Supino Reto','Peito'),
                 (11,'Supino Declinado','Peito'),
                 (12,'Crucifixo','Peito'),
                 (13,'Chin Up','Costas'),
                 (14,'Remada Curvada','Costas'),
                 (15,'Remada Alta','Costas'),
                 (16,'Remada unilateral','Costas'),
                 (17,'Lat Pull Down','Costas'),
                 (18,'Press Militar em Pé','Ombros'),
                 (19,'Elevações Laterais Cabo','Ombros'),
                 (20,'Elevações Frontais Halteres','Ombros'),
                 (21,'Arnold Press','Ombros'),
                 (22,'Corrida','Cardio');